<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesTableSeeder extends Seeder {

    /** Run the database seeds.
     * @return void */
    public function run() {

        DB::table('paises')->insert([
            // América do Sul
            ['nome' => 'Brasil', 'sigla' => 'BR', 'ddi' => '+55', 'iName' => 'Brazil', 'geoNameId' => '3469034'],
            ['nome' => 'Argentina', 'sigla' => 'AR', 'ddi' => '+54', 'iName' => 'Argentina', 'geoNameId' => '3865483'],
            ['nome' => 'Bolívia', 'sigla' => 'BO', 'ddi' => '+591', 'iName' => 'Bolivia', 'geoNameId' => '3923057'],
            ['nome' => 'Chile', 'sigla' => 'CL', 'ddi' => '+56', 'iName' => 'Chile', 'geoNameId' => '3895114'],
            ['nome' => 'Colômbia', 'sigla' => 'CO', 'ddi' => '+57', 'iName' => 'Colombia', 'geoNameId' => '3686110'],
            ['nome' => 'Equador', 'sigla' => 'EC', 'ddi' => '+593', 'iName' => 'Ecuador', 'geoNameId' => '3658394'],
            ['nome' => 'Guiana', 'sigla' => 'GY', 'ddi' => '+592', 'iName' => 'Guyana', 'geoNameId' => '3378535'],
            ['nome' => 'Paraguai', 'sigla' => 'PY', 'ddi' => '+595', 'iName' => 'Paraguay', 'geoNameId' => '3437598'],
            ['nome' => 'Peru', 'sigla' => 'PE', 'ddi' => '+51', 'iName' => 'Peru', 'geoNameId' => '3932488'],
            ['nome' => 'Suriname', 'sigla' => 'SR', 'ddi' => '+597', 'iName' => 'Suriname', 'geoNameId' => '3382998'],
            ['nome' => 'Uruguai', 'sigla' => 'UY', 'ddi' => '+598', 'iName' => 'Uruguay', 'geoNameId' => '3439705'],
            ['nome' => 'Venezuela', 'sigla' => 'VE', 'ddi' => '+58', 'iName' => 'Venezuela', 'geoNameId' => '3625428'],
            ['nome' => 'Ilhas Malvinas', 'sigla' => 'FK', 'ddi' => '+500', 'iName' => 'Falkland Islands', 'geoNameId' => '3474414'],
            ['nome' => 'Guiana Francesa', 'sigla' => 'GF', 'ddi' => '+594', 'iName' => 'French Guiana', 'geoNameId' => '3381670'],
            // América do Norte e Central
            ['nome' => 'Antígua e Barbuda', 'sigla' => 'AG', 'ddi' => '+1', 'iName' => 'Antigua and Barbuda', 'geoNameId' => '3576396'],
            ['nome' => 'Bahamas', 'sigla' => 'BS', 'ddi' => '+1', 'iName' => 'Bahamas', 'geoNameId' => '3572887'],
            ['nome' => 'Barbados', 'sigla' => 'BB', 'ddi' => '+1', 'iName' => 'Barbados', 'geoNameId' => '3374084'],
            ['nome' => 'Belize', 'sigla' => 'BZ', 'ddi' => '+501', 'iName' => 'Belize', 'geoNameId' => '3582678'],
            ['nome' => 'Canadá', 'sigla' => 'CA', 'ddi' => '+1', 'iName' => 'Canada', 'geoNameId' => '6251999'],
            ['nome' => 'Costa Rica', 'sigla' => 'CR', 'ddi' => '+506', 'iName' => 'Costa Rica', 'geoNameId' => '3624060'],
            ['nome' => 'Cuba', 'sigla' => 'CU', 'ddi' => '+53', 'iName' => 'Cuba', 'geoNameId' => '3562981'],
            ['nome' => 'Dominica', 'sigla' => 'DM', 'ddi' => '+1', 'iName' => 'Dominica', 'geoNameId' => '3575830'],
            ['nome' => 'República Dominicana', 'sigla' => 'DO', 'ddi' => '+1', 'iName' => 'Dominican Republic', 'geoNameId' => '3508796'],
            ['nome' => 'El Salvador', 'sigla' => 'SV', 'ddi' => '+503', 'iName' => 'El Salvador', 'geoNameId' => '3585968'],
            ['nome' => 'Granada', 'sigla' => 'GD', 'ddi' => '+1', 'iName' => 'Grenada', 'geoNameId' => '3580239'],
            ['nome' => 'Guatemala', 'sigla' => 'GT', 'ddi' => '+502', 'iName' => 'Guatemala', 'geoNameId' => '3595528'],
            ['nome' => 'Haiti', 'sigla' => 'HT', 'ddi' => '+509', 'iName' => 'Haiti', 'geoNameId' => '3723988'],
            ['nome' => 'Honduras', 'sigla' => 'HN', 'ddi' => '+504', 'iName' => 'Honduras', 'geoNameId' => '3608932'],
            ['nome' => 'Jamaica', 'sigla' => 'JM', 'ddi' => '+1', 'iName' => 'Jamaica', 'geoNameId' => '3489940'],
            ['nome' => 'México', 'sigla' => 'MX', 'ddi' => '+52', 'iName' => 'Mexico', 'geoNameId' => '3996063'],
            ['nome' => 'Nicarágua', 'sigla' => 'NI', 'ddi' => '+505', 'iName' => 'Nicaragua', 'geoNameId' => '3617476'],
            ['nome' => 'Panamá', 'sigla' => 'PA', 'ddi' => '+507', 'iName' => 'Panama', 'geoNameId' => '3703430'],
            ['nome' => 'Santa Lúcia', 'sigla' => 'LC', 'ddi' => '+1', 'iName' => 'Saint Lucia', 'geoNameId' => '3576468'],
            ['nome' => 'São Cristóvão e Nevis', 'sigla' => 'KN', 'ddi' => '+1', 'iName' => 'St Kitts and Nevis', 'geoNameId' => '3575174'],
            ['nome' => 'São Vicente e Granadinas', 'sigla' => 'VC', 'ddi' => '+1', 'iName' => 'St Vincent and Grenadines', 'geoNameId' => '3577815'],
            ['nome' => 'Trinidad e Tobago', 'sigla' => 'TT', 'ddi' => '+1', 'iName' => 'Trinidad and Tobago', 'geoNameId' => '3573591'],
            ['nome' => 'Estados Unidos da América', 'sigla' => 'US', 'ddi' => '+1', 'iName' => 'United States', 'geoNameId' => '6252001'],
            ['nome' => 'Anguilla', 'sigla' => 'AI', 'ddi' => '+1', 'iName' => 'Anguilla', 'geoNameId' => '3573511'],
            ['nome' => 'Bermudas', 'sigla' => 'BM', 'ddi' => '+1', 'iName' => 'Bermuda', 'geoNameId' => '3573345'],
            ['nome' => 'Ilhas Virgens Britânicas', 'sigla' => 'VG', 'ddi' => '+1', 'iName' => 'British Virgin Islands', 'geoNameId' => '3577718'],
            ['nome' => 'Ilhas Cayman', 'sigla' => 'KY', 'ddi' => '+1', 'iName' => 'Cayman Islands', 'geoNameId' => '3580718'],
            ['nome' => 'Groenlândia', 'sigla' => 'GL', 'ddi' => '+299', 'iName' => 'Greenland', 'geoNameId' => '3425505'],
            ['nome' => 'Guadalupe	', 'sigla' => 'GP', 'ddi' => '+590', 'iName' => 'Guadeloupe', 'geoNameId' => '3579143'],
            ['nome' => 'Martinica', 'sigla' => 'MQ', 'ddi' => '+596', 'iName' => 'Martinique', 'geoNameId' => '3570311'],
            ['nome' => 'Montserrat', 'sigla' => 'MS', 'ddi' => '+1', 'iName' => 'Montserrat', 'geoNameId' => '3578097'],
            ['nome' => 'Porto Rico', 'sigla' => 'PR', 'ddi' => '+1', 'iName' => 'Puerto Rico', 'geoNameId' => '4566966'],
            ['nome' => 'Saint-Pierre e Miquelon', 'sigla' => 'PM', 'ddi' => '+508', 'iName' => 'Saint Pierre and Miquelon', 'geoNameId' => '3424932'],
            ['nome' => 'Ilhas Turcas e Caicos', 'sigla' => 'TC', 'ddi' => '+1', 'iName' => 'Turks and Caicos Islands', 'geoNameId' => '3576916'],
            ['nome' => 'Ilhas Virgens Americanas', 'sigla' => 'VI', 'ddi' => '+1', 'iName' => 'U.S. Virgin Islands', 'geoNameId' => '4796775'],
            ['nome' => 'Aruba', 'sigla' => 'AW', 'ddi' => '+297', 'iName' => 'Aruba', 'geoNameId' => '3577279'],
            ['nome' => 'Países Baixos Caribenhos', 'sigla' => 'BQ', 'ddi' => '+599', 'iName' => 'Bonaire, Sint Eustatius, and Saba', 'geoNameId' => '7626844'],
            ['nome' => 'Curaçau', 'sigla' => 'CW', 'ddi' => '+599-9', 'iName' => 'Curaçao', 'geoNameId' => '7626836'],
            ['nome' => 'São Bartolomeu', 'sigla' => 'BL', 'ddi' => '+590', 'iName' => 'Saint Barthélemy', 'geoNameId' => '3578476'],
            ['nome' => 'São Martinho (França)', 'sigla' => 'MF', 'ddi' => '+590', 'iName' => 'Saint Martin', 'geoNameId' => '3578421'],
            ['nome' => 'São Martinho (Países Baixos)', 'sigla' => 'SX', 'ddi' => '+599', 'iName' => 'Sint Maarten', 'geoNameId' => '7609695'],
            // Europa
            ['nome' => 'Albânia', 'sigla' => 'AL', 'ddi' => '+355', 'iName' => 'Albania', 'geoNameId' => '783754'],
            ['nome' => 'Andorra', 'sigla' => 'AD', 'ddi' => '+376', 'iName' => 'Andorra', 'geoNameId' => '3041565'],
            ['nome' => 'Áustria', 'sigla' => 'AT', 'ddi' => '+43', 'iName' => 'Austria', 'geoNameId' => '2782113'],
            ['nome' => 'Bielorrússia', 'sigla' => 'BY', 'ddi' => '+375', 'iName' => 'Belarus', 'geoNameId' => '630336'],
            ['nome' => 'Bélgica', 'sigla' => 'BE', 'ddi' => '+32', 'iName' => 'Belgium', 'geoNameId' => '2802361'],
            ['nome' => 'Bósnia e Herzegovina', 'sigla' => 'BA', 'ddi' => '+387', 'iName' => 'Bosnia and Herzegovina', 'geoNameId' => '3277605'],
            ['nome' => 'Bulgária', 'sigla' => 'BG', 'ddi' => '+359', 'iName' => 'Bulgaria', 'geoNameId' => '732800'],
            ['nome' => 'Croácia', 'sigla' => 'HR', 'ddi' => '+385', 'iName' => 'Croatia', 'geoNameId' => '3202326'],
            ['nome' => 'Chipre', 'sigla' => 'CY', 'ddi' => '+357', 'iName' => 'Cyprus', 'geoNameId' => '146669'],
            ['nome' => 'Tchéquia', 'sigla' => 'CZ', 'ddi' => '+420', 'iName' => 'Czechia', 'geoNameId' => '3077311'],
            ['nome' => 'Dinamarca', 'sigla' => 'DK', 'ddi' => '+45', 'iName' => 'Denmark', 'geoNameId' => '2623032'],
            ['nome' => 'Estônia', 'sigla' => 'EE', 'ddi' => '+372', 'iName' => 'Estonia', 'geoNameId' => '453733'],
            ['nome' => 'Finlândia', 'sigla' => 'FI', 'ddi' => '+358', 'iName' => 'Finland', 'geoNameId' => '660013'],
            ['nome' => 'França', 'sigla' => 'FR', 'ddi' => '+33', 'iName' => 'France', 'geoNameId' => '3017382'],
            ['nome' => 'Alemanha', 'sigla' => 'DE', 'ddi' => '+49', 'iName' => 'Germany', 'geoNameId' => '2921044'],
            ['nome' => 'Grécia', 'sigla' => 'GR', 'ddi' => '+30', 'iName' => 'Greece', 'geoNameId' => '390903'],
            ['nome' => 'Hungria', 'sigla' => 'HU', 'ddi' => '+36', 'iName' => 'Hungary', 'geoNameId' => '719819'],
            ['nome' => 'Islândia', 'sigla' => 'IS', 'ddi' => '+354', 'iName' => 'Iceland', 'geoNameId' => '2629691'],
            ['nome' => 'Irlanda', 'sigla' => 'IE', 'ddi' => '+353', 'iName' => 'Ireland', 'geoNameId' => '2963597'],
            ['nome' => 'Itália', 'sigla' => 'IT', 'ddi' => '+39', 'iName' => 'Italy', 'geoNameId' => '3175395'],
            ['nome' => 'Kosovo', 'sigla' => 'XK', 'ddi' => '+383', 'iName' => 'Kosovo', 'geoNameId' => '831053'],
            ['nome' => 'Letônia', 'sigla' => 'LV', 'ddi' => '+371', 'iName' => 'Latvia', 'geoNameId' => '458258'],
            ['nome' => 'Liechtenstein', 'sigla' => 'LI', 'ddi' => '+423', 'iName' => 'Liechtenstein', 'geoNameId' => '3042058'],
            ['nome' => 'Lituânia', 'sigla' => 'LT', 'ddi' => '+370', 'iName' => 'Lithuania', 'geoNameId' => '597427'],
            ['nome' => 'Luxemburgo	', 'sigla' => 'LU', 'ddi' => '+352', 'iName' => 'Luxembourg', 'geoNameId' => '2960313'],
            ['nome' => 'Malta', 'sigla' => 'MT', 'ddi' => '+356', 'iName' => 'Malta', 'geoNameId' => '2562770'],
            ['nome' => 'Moldávia', 'sigla' => 'MD', 'ddi' => '+373', 'iName' => 'Moldova', 'geoNameId' => '617790'],
            ['nome' => 'Mônaco', 'sigla' => 'MC', 'ddi' => '+377', 'iName' => 'Monaco', 'geoNameId' => '2993457'],
            ['nome' => 'Montenegro', 'sigla' => 'ME', 'ddi' => '+382', 'iName' => 'Montenegro', 'geoNameId' => '3194884'],
            ['nome' => 'Holanda', 'sigla' => 'NL', 'ddi' => '+31', 'iName' => 'Netherlands', 'geoNameId' => '2750405'],
            ['nome' => 'Macedônia do Norte ', 'sigla' => 'MK', 'ddi' => '+389', 'iName' => 'North Macedonia', 'geoNameId' => '718075'],
            ['nome' => 'Noruega', 'sigla' => 'NO', 'ddi' => '+47', 'iName' => 'Norway', 'geoNameId' => '3144096'],
            ['nome' => 'Polônia', 'sigla' => 'PL', 'ddi' => '+48', 'iName' => 'Poland', 'geoNameId' => '798544'],
            ['nome' => 'Portugal', 'sigla' => 'PT', 'ddi' => '+351', 'iName' => 'Portugal', 'geoNameId' => '2264397'],
            ['nome' => 'Romênia', 'sigla' => 'RO', 'ddi' => '+40', 'iName' => 'Romania', 'geoNameId' => '798549'],
            ['nome' => 'Rússia', 'sigla' => 'RU', 'ddi' => '+7', 'iName' => 'Russia', 'geoNameId' => '2017370'],
            ['nome' => 'São Marinho', 'sigla' => 'SM', 'ddi' => '+378', 'iName' => 'San Marino', 'geoNameId' => '3168068'],
            ['nome' => 'Sérvia', 'sigla' => 'RS', 'ddi' => '+381', 'iName' => 'Serbia', 'geoNameId' => '6290252'],
            ['nome' => 'Eslováquia', 'sigla' => 'SK', 'ddi' => '+421', 'iName' => 'Slovakia', 'geoNameId' => '3057568'],
            ['nome' => 'Eslovênia', 'sigla' => 'SI', 'ddi' => '+386', 'iName' => 'Slovenia', 'geoNameId' => '3190538'],
            ['nome' => 'Espanha', 'sigla' => 'ES', 'ddi' => '+34', 'iName' => 'Spain', 'geoNameId' => '2510769'],
            ['nome' => 'Suécia', 'sigla' => 'SE', 'ddi' => '+46', 'iName' => 'Sweden', 'geoNameId' => '2661886'],
            ['nome' => 'Suíça', 'sigla' => 'CH', 'ddi' => '+41', 'iName' => 'Switzerland', 'geoNameId' => '2658434'],
            ['nome' => 'Ucrânia', 'sigla' => 'UA', 'ddi' => '+380', 'iName' => 'Ukraine', 'geoNameId' => '690791'],
            ['nome' => 'Reino Unido', 'sigla' => 'GB', 'ddi' => '+44', 'iName' => 'United Kingdom', 'geoNameId' => '2635167'],
            ['nome' => 'Vaticano', 'sigla' => 'VA', 'ddi' => '+379', 'iName' => 'Vatican City', 'geoNameId' => '3164670'],
            ['nome' => 'Ilhas Féroe', 'sigla' => 'FO', 'ddi' => '+298', 'iName' => 'Faroe Islands', 'geoNameId' => '2622320'],
            ['nome' => 'Gibraltar', 'sigla' => 'GI', 'ddi' => '+350', 'iName' => 'Gibraltar', 'geoNameId' => '2411586'],
            ['nome' => 'Ilhas de Aland', 'sigla' => 'AX', 'ddi' => '+358', 'iName' => 'Åland', 'geoNameId' => '661882'],
            ['nome' => 'Svalbard e Jan Mayen', 'sigla' => 'SJ', 'ddi' => '+47', 'iName' => 'Svalbard and Jan Mayen', 'geoNameId' => '607072'],
            // Ásia
            ['nome' => 'Afeganistão', 'sigla' => 'AF', 'ddi' => '+93', 'iName' => 'Afghanistan', 'geoNameId' => '1149361'],
            ['nome' => 'Armênia', 'sigla' => 'AM', 'ddi' => '+374', 'iName' => 'Armenia', 'geoNameId' => '174982'],
            ['nome' => 'Azerbaijão', 'sigla' => 'AZ', 'ddi' => '+994', 'iName' => 'Azerbaijan', 'geoNameId' => '587116'],
            ['nome' => 'Bahrein', 'sigla' => 'BH', 'ddi' => '+973', 'iName' => 'Bahrain', 'geoNameId' => '290291'],
            ['nome' => 'Bangladesh', 'sigla' => 'BD', 'ddi' => '+880', 'iName' => 'Bangladesh', 'geoNameId' => '1210997'],
            ['nome' => 'Butão', 'sigla' => 'BT', 'ddi' => '+975', 'iName' => 'Bhutan', 'geoNameId' => '1252634'],
            ['nome' => 'Brunei', 'sigla' => 'BN', 'ddi' => '+673', 'iName' => 'Brunei', 'geoNameId' => '1820814'],
            ['nome' => 'Camboja', 'sigla' => 'KH', 'ddi' => '+855', 'iName' => 'Cambodia', 'geoNameId' => '1831722'],
            ['nome' => 'China', 'sigla' => 'CN', 'ddi' => '+86', 'iName' => 'China', 'geoNameId' => '1814991'],
            ['nome' => 'Geórgia', 'sigla' => 'GE', 'ddi' => '+995', 'iName' => 'Georgia', 'geoNameId' => '614540'],
            ['nome' => 'Índia', 'sigla' => 'IN', 'ddi' => '+91', 'iName' => 'India', 'geoNameId' => '1269750'],
            ['nome' => 'Indonésia', 'sigla' => 'ID', 'ddi' => '+62', 'iName' => 'Indonesia', 'geoNameId' => '1643084'],
            ['nome' => 'Irã', 'sigla' => 'IR', 'ddi' => '+98', 'iName' => 'Iran', 'geoNameId' => '130758'],
            ['nome' => 'Iraque', 'sigla' => 'IQ', 'ddi' => '+964', 'iName' => 'Iraq', 'geoNameId' => '99237'],
            ['nome' => 'Israel', 'sigla' => 'IL', 'ddi' => '+972', 'iName' => 'Israel', 'geoNameId' => '294640'],
            ['nome' => 'Japão', 'sigla' => 'JP', 'ddi' => '+81', 'iName' => 'Japan', 'geoNameId' => '1861060'],
            ['nome' => 'Jordânia', 'sigla' => 'JO', 'ddi' => '+962', 'iName' => 'Jordan', 'geoNameId' => '248816'],
            ['nome' => 'Cazaquistão', 'sigla' => 'KZ', 'ddi' => '+7', 'iName' => 'Kazakhstan', 'geoNameId' => '1522867'],
            ['nome' => 'Kuwait', 'sigla' => 'KW', 'ddi' => '+965', 'iName' => 'Kuwait', 'geoNameId' => '285570'],
            ['nome' => 'Quirguistão', 'sigla' => 'KG', 'ddi' => '+996', 'iName' => 'Kyrgyzstan', 'geoNameId' => '1527747'],
            ['nome' => 'Laos', 'sigla' => 'LA', 'ddi' => '+856', 'iName' => 'Laos', 'geoNameId' => '1655842'],
            ['nome' => 'Líbano', 'sigla' => 'LB', 'ddi' => '+961', 'iName' => 'Lebanon', 'geoNameId' => '272103'],
            ['nome' => 'Malásia', 'sigla' => 'MY', 'ddi' => '+60', 'iName' => 'Malaysia', 'geoNameId' => '1733045'],
            ['nome' => 'Maldivas', 'sigla' => 'MV', 'ddi' => '+960', 'iName' => 'Maldives', 'geoNameId' => '1282028'],
            ['nome' => 'Mongólia', 'sigla' => 'MN', 'ddi' => '+976', 'iName' => 'Mongolia', 'geoNameId' => '2029969'],
            ['nome' => 'Myanmar', 'sigla' => 'MM', 'ddi' => '+95', 'iName' => 'Myanmar', 'geoNameId' => '1327865'],
            ['nome' => 'Nepal', 'sigla' => 'NP', 'ddi' => '+977', 'iName' => 'Nepal', 'geoNameId' => '1282988'],
            ['nome' => 'Coreia do Norte', 'sigla' => 'KP', 'ddi' => '+850', 'iName' => 'North Korea', 'geoNameId' => '1873107'],
            ['nome' => 'Omã', 'sigla' => 'OM', 'ddi' => '+968', 'iName' => 'Oman', 'geoNameId' => '286963'],
            ['nome' => 'Paquistão', 'sigla' => 'PK', 'ddi' => '+92', 'iName' => 'Pakistan', 'geoNameId' => '1168579'],
            ['nome' => 'Filipinas', 'sigla' => 'PH', 'ddi' => '+63', 'iName' => 'Philippines', 'geoNameId' => '1694008'],
            ['nome' => 'Qatar', 'sigla' => 'QA', 'ddi' => '+974', 'iName' => 'Qatar', 'geoNameId' => '289688'],
            ['nome' => 'Arábia Saudita', 'sigla' => 'SA', 'ddi' => '+966', 'iName' => 'Saudi Arabia', 'geoNameId' => '102358'],
            ['nome' => 'Singapura', 'sigla' => 'SG', 'ddi' => '+65', 'iName' => 'Singapore', 'geoNameId' => '1880251'],
            ['nome' => 'Coreia do Sul', 'sigla' => 'KR', 'ddi' => '+82', 'iName' => 'South Korea', 'geoNameId' => '1835841'],
            ['nome' => 'Sri Lanka', 'sigla' => 'LK', 'ddi' => '+94', 'iName' => 'Sri Lanka', 'geoNameId' => '1227603'],
            ['nome' => 'Síria', 'sigla' => 'SY', 'ddi' => '+963', 'iName' => 'Syria', 'geoNameId' => '163843'],
            ['nome' => 'Taiwan', 'sigla' => 'TW', 'ddi' => '+886', 'iName' => 'Taiwan', 'geoNameId' => '1668284'],
            ['nome' => 'Tadjiquistão', 'sigla' => 'TJ', 'ddi' => '+992', 'iName' => 'Tajikistan', 'geoNameId' => '1220409'],
            ['nome' => 'Tailândia', 'sigla' => 'TH', 'ddi' => '+66', 'iName' => 'Thailand', 'geoNameId' => '1605651'],
            ['nome' => 'Turquia', 'sigla' => 'TR', 'ddi' => '+90', 'iName' => 'Turkey', 'geoNameId' => '298795'],
            ['nome' => 'Turquemenistão', 'sigla' => 'TM', 'ddi' => '+993', 'iName' => 'Turkmenistan', 'geoNameId' => '1218197'],
            ['nome' => 'Emirados Árabes Unidos', 'sigla' => 'AE', 'ddi' => '+971', 'iName' => 'United Arab Emirates', 'geoNameId' => '290557'],
            ['nome' => 'Uzbequistão', 'sigla' => 'UZ', 'ddi' => '+998', 'iName' => 'Uzbekistan', 'geoNameId' => '1512440'],
            ['nome' => 'Vietnã', 'sigla' => 'VN', 'ddi' => '+84', 'iName' => 'Vietnam', 'geoNameId' => '1562822'],
            ['nome' => 'Iêmen', 'sigla' => 'YE', 'ddi' => '+967', 'iName' => 'Yemen', 'geoNameId' => '69543'],
            ['nome' => 'Território do Oceano Índico Britânico', 'sigla' => 'IO', 'ddi' => '+246', 'iName' => 'British Indian Ocean Territory', 'geoNameId' => '1282588'],
            ['nome' => 'Ilhas Cocos (Keeling)', 'sigla' => 'CC', 'ddi' => '+672', 'iName' => 'Cocos [Keeling] Islands', 'geoNameId' => '1547376'],
            ['nome' => 'Hong Kong', 'sigla' => 'HK', 'ddi' => '+852', 'iName' => 'Hong Kong', 'geoNameId' => '1819730'],
            ['nome' => 'Macau', 'sigla' => 'MO', 'ddi' => '+853', 'iName' => 'Macao', 'geoNameId' => '1821275'],
            ['nome' => 'Palestina', 'sigla' => 'PS', 'ddi' => '+970', 'iName' => 'Palestine', 'geoNameId' => '6254930'],
            // Oceania
            ['nome' => 'Austrália', 'sigla' => 'AU', 'ddi' => '+61', 'iName' => 'Australia', 'geoNameId' => '2077456'],
            ['nome' => 'Fiji', 'sigla' => 'FJ', 'ddi' => '+679', 'iName' => 'Fiji', 'geoNameId' => '2205218'],
            ['nome' => 'Kiribati', 'sigla' => 'KI', 'ddi' => '+686', 'iName' => 'Kiribati', 'geoNameId' => '4030945'],
            ['nome' => 'Nauru', 'sigla' => 'NR', 'ddi' => '+674', 'iName' => 'Nauru', 'geoNameId' => '2110425'],
            ['nome' => 'Nova Zelândia', 'sigla' => 'NZ', 'ddi' => '+64', 'iName' => 'New Zealand', 'geoNameId' => '2186224'],
            ['nome' => 'Papua-Nova Guiné', 'sigla' => 'PG', 'ddi' => '+675', 'iName' => 'Papua New Guinea', 'geoNameId' => '2088628'],
            ['nome' => 'Samoa', 'sigla' => 'WS', 'ddi' => '+685', 'iName' => 'Samoa', 'geoNameId' => '4034894'],
            ['nome' => 'Ilhas Salomão', 'sigla' => 'SB', 'ddi' => '+677', 'iName' => 'Solomon Islands', 'geoNameId' => '2103350'],
            ['nome' => 'Timor-Leste', 'sigla' => 'TL', 'ddi' => '+670', 'iName' => 'Timor-Leste', 'geoNameId' => '1966436'],
            ['nome' => 'Tonga', 'sigla' => 'TO', 'ddi' => '+676', 'iName' => 'Tonga', 'geoNameId' => '4032283'],
            ['nome' => 'Tuvalu', 'sigla' => 'TV', 'ddi' => '+688', 'iName' => 'Tuvalu', 'geoNameId' => '2110297'],
            ['nome' => 'Vanuatu', 'sigla' => 'VU', 'ddi' => '+678', 'iName' => 'Vanuatu', 'geoNameId' => '2134431'],
            ['nome' => 'Ilha Christmas', 'sigla' => 'CX', 'ddi' => '+672', 'iName' => 'Christmas Island', 'geoNameId' => '2078138'],
            ['nome' => 'Polinésia Francesa', 'sigla' => 'PF', 'ddi' => '+689', 'iName' => 'French Polynesia', 'geoNameId' => '4030656'],
            ['nome' => 'Guam', 'sigla' => 'GU', 'ddi' => '+671', 'iName' => 'Guam', 'geoNameId' => '4043988'],
            ['nome' => 'Nova Caledônia', 'sigla' => 'NC', 'ddi' => '+687', 'iName' => 'New Caledonia', 'geoNameId' => '2139685'],
            ['nome' => 'Ilha Norfolk', 'sigla' => 'NF', 'ddi' => '+672', 'iName' => 'Norfolk Island', 'geoNameId' => '2155115'],
            ['nome' => 'Ilhas Marianas do Norte', 'sigla' => 'MP', 'ddi' => '+1', 'iName' => 'Northern Mariana Islands', 'geoNameId' => '4041468'],
            ['nome' => 'Ilhas Picárnia', 'sigla' => 'PN', 'ddi' => '+64', 'iName' => 'Pitcairn Islands', 'geoNameId' => '4030699'],
            ['nome' => 'Tokelau', 'sigla' => 'TK', 'ddi' => '+690', 'iName' => 'Tokelau', 'geoNameId' => '4031074'],
            ['nome' => 'Ilhas Menores Afastadas dos Estados Unidos', 'sigla' => 'UM', 'ddi' => '+246', 'iName' => 'U.S. Minor Outlying Islands', 'geoNameId' => '5854968'],
            ['nome' => 'Wallis e Futuna', 'sigla' => 'WF', 'ddi' => '+681', 'iName' => 'Wallis and Futuna', 'geoNameId' => '4034749'],
            ['nome' => 'Ilhas Marshall', 'sigla' => 'MH', 'ddi' => '+692', 'iName' => 'Marshall Islands', 'geoNameId' => '2080185'],
            ['nome' => 'Estados Federados da Micronésia', 'sigla' => 'FM', 'ddi' => '+691', 'iName' => 'Micronesia', 'geoNameId' => '2081918'],
            ['nome' => 'Palau', 'sigla' => 'PW', 'ddi' => '+680', 'iName' => 'Palau', 'geoNameId' => '1559582'],
            ['nome' => 'Ilhas Cook', 'sigla' => 'CK', 'ddi' => '+682', 'iName' => 'Cook Islands', 'geoNameId' => '1899402'],
            ['nome' => 'Niue', 'sigla' => 'NU', 'ddi' => '+683', 'iName' => 'Niue', 'geoNameId' => '4036232'],
            ['nome' => 'Samoa Americana', 'sigla' => 'AS', 'ddi' => '+1', 'iName' => 'American Samoa', 'geoNameId' => '5880801'],
            //['nome' => 'Coral Sea Islands Territory', 'sigla' => 'AU', 'ddi' => '+', 'iName' => 'Coral Sea Islands Territory', 'geoNameId' => '2170371'],
            // ['nome' => 'Território da Baía de Jervis', 'sigla' => 'AU', 'ddi' => '+61', 'iName' => 'Jervis Bay Territory', 'geoNameId' => '8335033'],
            // ['nome' => 'Território das ilhas Ashmore e Cartier', 'sigla' => 'AU', 'ddi' => '+', 'iName' => 'Territory of Ashmore and Cartier Islands', 'geoNameId' => '2077507'],
            // África
            ['nome' => 'Argélia', 'sigla' => 'DZ', 'ddi' => '+213', 'iName' => 'Algeria', 'geoNameId' => '2589581'],
            ['nome' => 'Angola', 'sigla' => 'AO', 'ddi' => '+244', 'iName' => 'Angola', 'geoNameId' => '3351879'],
            ['nome' => 'Benin', 'sigla' => 'BJ', 'ddi' => '+229', 'iName' => 'Benin', 'geoNameId' => '2395170'],
            ['nome' => 'Botswana', 'sigla' => 'BW', 'ddi' => '+267', 'iName' => 'Botswana', 'geoNameId' => '933860'],
            ['nome' => 'Burkina Faso', 'sigla' => 'BF', 'ddi' => '+226', 'iName' => 'Burkina Faso', 'geoNameId' => '2361809'],
            ['nome' => 'Burundi', 'sigla' => 'BI', 'ddi' => '+257', 'iName' => 'Burundi', 'geoNameId' => '433561'],
            ['nome' => 'Cabo Verde', 'sigla' => 'CV', 'ddi' => '+238', 'iName' => 'Cabo Verde', 'geoNameId' => '3374766'],
            ['nome' => 'Camarões', 'sigla' => 'CM', 'ddi' => '+237', 'iName' => 'Cameroon', 'geoNameId' => '2233387'],
            ['nome' => 'República Centro-Africana', 'sigla' => 'CF', 'ddi' => '+236', 'iName' => 'Central African Republic', 'geoNameId' => '239880'],
            ['nome' => 'Chade', 'sigla' => 'TD', 'ddi' => '+237', 'iName' => 'Chad', 'geoNameId' => '2434508'],
            ['nome' => 'Comores', 'sigla' => 'KM', 'ddi' => '+269', 'iName' => 'Comoros', 'geoNameId' => '921929'],
            ['nome' => 'Congo-Brazzaville', 'sigla' => 'CG', 'ddi' => '+242', 'iName' => 'Congo', 'geoNameId' => '2260494'],
            ['nome' => 'República Democrática do Congo', 'sigla' => 'CD', 'ddi' => '+243', 'iName' => 'DR Congo', 'geoNameId' => '203312'],
            ['nome' => 'Djibuti', 'sigla' => 'DJ', 'ddi' => '+253', 'iName' => 'Djibouti', 'geoNameId' => '223816'],
            ['nome' => 'Egito', 'sigla' => 'EG', 'ddi' => '+20', 'iName' => 'Egypt', 'geoNameId' => '357994'],
            ['nome' => 'Guiné Equatorial', 'sigla' => 'GQ', 'ddi' => '+240', 'iName' => 'Equatorial Guinea', 'geoNameId' => '2309096'],
            ['nome' => 'Eritreia', 'sigla' => 'ER', 'ddi' => '+291', 'iName' => 'Eritrea', 'geoNameId' => '338010'],
            ['nome' => 'Suazilândia', 'sigla' => 'SZ', 'ddi' => '+268', 'iName' => 'Eswatini', 'geoNameId' => '934841'],
            ['nome' => 'Etiópia', 'sigla' => 'ET', 'ddi' => '+251', 'iName' => 'Ethiopia', 'geoNameId' => '337996'],
            ['nome' => 'Gabão', 'sigla' => 'GA', 'ddi' => '+241', 'iName' => 'Gabon', 'geoNameId' => '2400553'],
            ['nome' => 'Gâmbia', 'sigla' => 'GM', 'ddi' => '+220', 'iName' => 'Gambia', 'geoNameId' => '2413451'],
            ['nome' => 'Gana', 'sigla' => 'GH', 'ddi' => '+233', 'iName' => 'Ghana', 'geoNameId' => '2300660'],
            ['nome' => 'Guiné', 'sigla' => 'GN', 'ddi' => '+224', 'iName' => 'Guinea', 'geoNameId' => '2420477'],
            ['nome' => 'Guiné-Bissau', 'sigla' => 'GW', 'ddi' => '+245', 'iName' => 'Guinea-Bissau', 'geoNameId' => '2372248'],
            ['nome' => 'Costa do Marfim', 'sigla' => 'CI', 'ddi' => '+225', 'iName' => 'Ivory Coast', 'geoNameId' => '2287781'],
            ['nome' => 'Quênia', 'sigla' => 'KE', 'ddi' => '+254', 'iName' => 'Kenya', 'geoNameId' => '192950'],
            ['nome' => 'Lesoto', 'sigla' => 'LS', 'ddi' => '+266', 'iName' => 'Lesotho', 'geoNameId' => '932692'],
            ['nome' => 'Libéria', 'sigla' => 'LR', 'ddi' => '+231', 'iName' => 'Liberia', 'geoNameId' => '2275384'],
            ['nome' => 'Líbia', 'sigla' => 'LY', 'ddi' => '+218', 'iName' => 'Libya', 'geoNameId' => '2215636'],
            ['nome' => 'Madagascar', 'sigla' => 'MG', 'ddi' => '+261', 'iName' => 'Madagascar', 'geoNameId' => '1062947'],
            ['nome' => 'Malawi', 'sigla' => 'MW', 'ddi' => '+265', 'iName' => 'Malawi', 'geoNameId' => '927384'],
            ['nome' => 'Mali', 'sigla' => 'ML', 'ddi' => '+223', 'iName' => 'Mali', 'geoNameId' => '2453866'],
            ['nome' => 'Mauritânia', 'sigla' => 'MR', 'ddi' => '+222', 'iName' => 'Mauritania', 'geoNameId' => '2378080'],
            ['nome' => 'Maurício', 'sigla' => 'MU', 'ddi' => '+230', 'iName' => 'Mauritius', 'geoNameId' => '934292'],
            ['nome' => 'Marrocos', 'sigla' => 'MA', 'ddi' => '+212', 'iName' => 'Morocco', 'geoNameId' => '2542007'],
            ['nome' => 'Moçambique', 'sigla' => 'MZ', 'ddi' => '+258', 'iName' => 'Mozambique', 'geoNameId' => '1036973'],
            ['nome' => 'Namíbia', 'sigla' => 'NA', 'ddi' => '+264', 'iName' => 'Namibia', 'geoNameId' => '3355338'],
            ['nome' => 'Níger', 'sigla' => 'NE', 'ddi' => '+227', 'iName' => 'Niger', 'geoNameId' => '2440476'],
            ['nome' => 'Nigéria', 'sigla' => 'NG', 'ddi' => '+234', 'iName' => 'Nigeria', 'geoNameId' => '2328926'],
            ['nome' => 'Ruanda', 'sigla' => 'RW', 'ddi' => '+250', 'iName' => 'Rwanda', 'geoNameId' => '49518'],
            ['nome' => 'Senegal', 'sigla' => 'SN', 'ddi' => '+221', 'iName' => 'Senegal', 'geoNameId' => '2245662'],
            ['nome' => 'Seicheles', 'sigla' => 'SC', 'ddi' => '+248', 'iName' => 'Seychelles', 'geoNameId' => '241170'],
            ['nome' => 'Serra Leoa', 'sigla' => 'SL', 'ddi' => '+232', 'iName' => 'Sierra Leone', 'geoNameId' => '2403846'],
            ['nome' => 'Somália', 'sigla' => 'SO', 'ddi' => '+252', 'iName' => 'Somalia', 'geoNameId' => '51537'],
            ['nome' => 'África do Sul', 'sigla' => 'ZA', 'ddi' => '+27', 'iName' => 'South Africa', 'geoNameId' => '953987'],
            ['nome' => 'Sudão do Sul', 'sigla' => 'SS', 'ddi' => '+211', 'iName' => 'South Sudan', 'geoNameId' => '7909807'],
            ['nome' => 'Sudão', 'sigla' => 'SD', 'ddi' => '+249', 'iName' => 'Sudan', 'geoNameId' => '366755'],
            ['nome' => 'São Tomé e Príncipe', 'sigla' => 'ST', 'ddi' => '+239', 'iName' => 'São Tomé and Príncipe', 'geoNameId' => '2410758'],
            ['nome' => 'Tanzânia', 'sigla' => 'TZ', 'ddi' => '+255', 'iName' => 'Tanzania', 'geoNameId' => '149590'],
            ['nome' => 'Togo', 'sigla' => 'TG', 'ddi' => '+228', 'iName' => 'Togo', 'geoNameId' => '2363686'],
            ['nome' => 'Tunísia', 'sigla' => 'TN', 'ddi' => '+216', 'iName' => 'Tunisia', 'geoNameId' => '2464461'],
            ['nome' => 'Uganda', 'sigla' => 'UG', 'ddi' => '+256', 'iName' => 'Uganda', 'geoNameId' => '226074'],
            ['nome' => 'Zâmbia', 'sigla' => 'ZM', 'ddi' => '+260', 'iName' => 'Zambia', 'geoNameId' => '895949'],
            ['nome' => 'Zimbábue', 'sigla' => 'ZW', 'ddi' => '+263', 'iName' => 'Zimbabwe', 'geoNameId' => '878675'],
            ['nome' => 'Mayotte', 'sigla' => 'YT', 'ddi' => '+269', 'iName' => 'Mayotte', 'geoNameId' => '1024031'],
            ['nome' => 'Reunião', 'sigla' => 'RE', 'ddi' => '+262', 'iName' => 'Réunion', 'geoNameId' => '935317'],
            ['nome' => 'Santa Helena', 'sigla' => 'SH', 'ddi' => '+290', 'iName' => 'Saint Helena', 'geoNameId' => '3370751'],
            ['nome' => 'Saara Ocidental', 'sigla' => 'EH', 'ddi' => '+212', 'iName' => 'Western Sahara', 'geoNameId' => '2461445']
         ]);

         $this->command->info('Países cadastrados com sucesso!');
    }
}
